# source: https://senorasenora.files.wordpress.com/2018/09/a_frequency_dictionary_of_spanish.pdf

# fuction words, all inc regardless of freq

article = {
    'el' : 'the',
    'la' : 'the',
    'un' : ['a', 'an']
}

conjunction = {
    'que' : ['that', 'which'],
    'y' : 'and',
    'como' : ['like', 'as'],
    'pero' : ['but', 'yet', 'except'],
    'o' : 'or',
    'si' : ['if', 'whether'],
    'porque' : 'because',
    'cuando' : 'when',
    'ni' : ['not even', 'neither', 'nor'],
	 'donde' : 'where',
	 'pues' : ['then', 'well then'],
	 'sino' : ['but', 'except', 'rather'],
	 'aunque' : ['although', 'even though'],
	 'mientras' : ['while', 'whereas', 'as long as'],
	 'mas' : ['but', 'however']
}

interjection = {
	'ah' : 'oh',
	'ay' : ['oh no!', 'oh my!'],
	'eh' : 'eh',
	'oh' : 'oh',
	'hola' : ['hello', 'hi']
}

preposition = {
	'de' : ['of', 'from'],
	'a' : ['to', 'at'],
	'en' : ['in', 'on'],
	'por' : ['by', 'for', 'through'],
	'con' : 'with',
	'para' : ['for', 'to', 'in order to'],
	'sin' : 'without',
	'sobre' : ['on top of', 'over', 'about'],
	'hasta' : ['until', 'up to', 'even'],
	'entre' : ['between', 'among'],
	'desde' : ['from', 'since'],
	'hacia' : ['toward', 'towards'],
	'contra' : ['against', 'opposite'],
	'bajo' : ['under', 'underneath'],
	'ante' : ['before', 'in the presence of'],
	'segun' : 'according to',
	'tras' : ['after', 'behind'],
	'mediante' : 'by means of',
	'excepto' : 'except'
}

number = {
	'cero' : ['zero', 'naught', 'nil'],
	'uno' : 'one',
	'dos' : 'two',
	'tres' : 'three',
	'cuatro' : 'four',
	'cinco' : 'five',
	'seis' : 'six',
	'siete' : 'seven',
	'ocho' : 'eight',
	'nueve' : 'nine',
	'diez' : 'ten',
	'once' : 'eleven',
	'doce' : 'twelve',
	'trece' : 'thirteen',
	'catorce' : 'fourteen',
	'quince' : 'fifteen',
	'dieciseis' : 'sixteen',
	'de diecisiete' : 'seventeen',
	'dieciocho' : 'eighteen',
	'diecinueve' : 'nineteen',
	'veinte' : 'twenty',
	'veintiuno' : 'twenty one',
	'veintidos': 'twenty two',
	'veintitres' : 'twenty three',
	'treinta' : 'thirty',
	'treinta y uno' : 'thirty one',
	'treinta y dos' : 'thirty two',
	'treinta y tres' : 'thirty three',
	'cuarenta' : 'fourty',
	'cincuenta' : 'fifty',
	'sesenta' : 'sixty',
	'setenta' : 'seventy',
	'ochenta' : 'eighty',
	'noventa' : 'ninety',
	'cien' : 'hundred',
	'ciento diez' : 'hundred ten',
	'ciento veintidos' : 'hundred twenty two',
	'ciento treinta y tres' : 'hundred thirty three',
	'doscientos' : 'two hundred',
	'trescientos' : 'three hundred',
	'mil' : 'thousand',
	'mil cien' : 'thousand hundred',
	'mil docientos' : 'thousand two hundred',
	'mil trescientos' : 'thousand three hundred',
	'diez mil' : 'ten thousand',
	'veinte mil' : 'twenty thousand',
	'treinta mil' : 'thirty thousand',
	'cien mil' : 'hundred thousand',
	'doscientos mil' : 'two hundred thousand',
	'trescientos mil' : 'three hundred thousand',
	'millon' : 'million',
	'dos millones' : 'two million',
	'tres millones' : 'three million',
	'diez millones' : 'ten million',
	'viente millones' : 'twenty million',
	'treinta millones' : 'thirty million',
	'cien millones' : 'hundred million',
	'mil millones' : 'billion',
	'cien mil millones' : 'hundred billion'
}

pronoun = {
	'se' : 'be',
	'me' : 'me',
	'te' : 'you',
	'lo' : 'him',
	'la' : 'her',
	'le' : ['to him', 'to her'],
	'nos' : 'us',
	'les' : 'you all',
	'los' : 'them',
	'las' : 'them',
	'les' : 'to them'
	'el' : 'he',
	'que' : ['what?', 'which?', 'how!'],
	'yo' : 'I',
	'eso' : 'that',
	'ella' : 'she',
	'nada' : 'nothing',
	'algo' : ['something', 'somewhat'],
	'esto' : 'this',
	'quien' : ['who', 'whom'],
	'cual' : ['which', 'who', 'whom'],
	'este' : 'this one',
	'nosotros' : 'we',
	'nadie' : ['nobody', 'anybody'],
	'usted' : 'you',
	'quien' : ['who?', 'whom?'],
	'ello' : 'it',
	'mi' : 'me',
	'cual' : 'which?'
	'alguien' : ['somebody', 'someone', 'anyone'],
	'suyo' : ['his', 'hers', 'yours', 'theirs'],
	'tu' : 'you',
	'aquello' : 'that over there',
	'ese' : 'that one',
	'mio' : 'mine',
	'os' : 'you',
	'aquel' : 'that one over there',
	'ti' : 'you',
	'conmigo' : 'with me',
	'tuyo' : 'yours',
	'contigo' : 'with you',
	'vos' : 'you',
	'vosotros' : 'you'
}

# lexical words, only if freq < 1k

adjective = {
	'su' : ['his', 'her', 'their', 'your'],
	'lo' : 'the',
	'todo' : ['all', 'every'],
	'mas' : 'more',
	'este' : 'this',
	'otro' : ['other', 'another'],
	'ese' : 'that',
	'mucho' : ['much', 'many', 'a lot'],
	'mi' : 'my',
	'alguno' : ['some', 'someone'],
	'mismo' : 'same',
	'primero' : 'first',
	'grande' : ['large', 'great', 'big'],
	'poco' : ['little', 'few', 'a little bit'],
	'tanto' : ['so much', 'so many'],
	'neustro' : 'our',
	'cada' : ['each', 'every'],
	'menos' : ['less', 'fewer'],
	'nuevo' : 'new',
	'aquel' : 'that',
	'bueno' : 'good',
	'tal' : 'such',
	'mejor' : ['best', 'better'],
	'cierto' : ['certain', 'sure', 'true'],
	'mayor' : ['larger', 'older', 'main'],
	'ultimo' : ['last', 'final'],
	'propio' : ['own', 'proper', 'typical'],
	'ninguno' : ['no', 'none', 'nobody'],
    'cualquier' : ['any', 'anyone'],
    'solo' : ['lonely', 'alone'],
    'largo' : 'long',
    'unico' : ['only', 'unique', 'sole'],
    'peqeno' : ['little', 'small', 'young'],
    'alto' : ['tall', 'high'],
    'importante' : 'important',
    'medio' : ['half', 'middle'],
    'cuanto' : 'regarding',
    'humano' : 'human',
    'varios' : ['severa', 'various'],
    'posible' : 'possible',
    'general' : 'general',
    'igual' : ['equal', 'same'],
    'segundo' : 'second',
    'blanco' : 'white',
    'distinto' : ['distinct', 'different'],
    'claro' : 'clear',
    'cuyo' : 'whose',
    'bastante' : ['rather', 'fairly', 'quite a bit'],
    'malo' : 'bad',
    'social' : 'social',
    'viejo' : ['old', 'aged'],
    'politico' : 'political',
    'espanol' : 'Spanish',
    'siguiente' : ['following', 'next'],
    'demas' : ['the rset', 'others'],
    'dificil' : ['difficult', 'hard'],
    'negro' : 'black',
    'necesario' : 'necessary',
    'menor' : ['younger', 'youngest'],
    'demasiado' : ['too much', 'too many'],
    'antiguo' : ['old', 'ancient', 'former'],
    'tu' : 'your',
    'especial' : 'special',
    'diferente' : ['different', 'separate'],
    'anterior' : ['previous', 'preceding'],
    'pobre' : 'poor',
    'tercero' : 'third',
    'capaz' : ['capable', 'able'],
    'bajo': ['short', 'low'],
    'libre' : ['free', 'vacant'],
    'natural' : 'natural',
    'verdadero' : ['true', 'real'],
    'economico' : 'economic',
    'comun' : 'common',
    'abierto' : ['open', 'unlocked'],
    'proximo' : 'next',
    'joven' : 'young',
    'pasado' : ['past', 'last'],
    'vivo' : ['alive', 'bright'],
    'completo' : 'complete',
    'contrario' : ['contrary', 'opposite'],
    'real' : ['royal', 'real', 'authentic'],
    'publico' : 'public',
    'enorme' : ['enormous', 'vast'],
    'ambos' : 'both',
    'profundo' : ['deep', 'profound'],
    'principal' : ['main', 'principal'],
    'nacional' : 'national',
    'lleno' : ['full', 'filled'],
    'supuesto' : ['supposed'],
    'por supuesto' : 'of course',
    'facil' : 'easy',
    'rojo' : 'red',
    'superior' : ['superior', 'upper'],
    'corto' : ['short', 'brief'],
    'conocido' : ['known', 'well known'],
    'serio' : 'serious',
    'suficiente' : ['sufficient', 'enough'],
    'grave' : ['serious', 'solemn'],
    'extrano' : ['strange', 'foreign'],
    'absoluto' : 'absolute',
    'personal' : 'peronal',
    'imposible' : 'impossible',
    'ingles' : 'English',
    'duro' : 'hard',
    'rico' : ['rich', 'tasty'],
    'total' : ['total', 'entire'],
    'puro' : ['pure', 'clean'],
    'profesional' : 'professional',
    'fisico' : 'physical',
    'frances' : 'French',
    'rapido' : ['quick', 'fast'],
    'simple' : ['simple', 'mere', 'simple minded'],
    'normal' : ['normal', 'usual', 'regular'],
    'moderno' : 'modern',
    'actual' : 'current',
    'pleno' : ['complete', 'full'],
    'cerrado' : 'closed',
    'muerto' : 'dead',
    'dispuesto' : ['willing', 'ready'],
    'enfermo' : ['ill', 'sick'],
    'privado' : 'private',
    'popular' : 'popular',
    'famoso' : ['famous', 'well known'],
    'cuanto' : 'how much?',
    'inmediato' : 'immediate',
    'junto' : 'together',
    'directo' : ['direct', 'straight'],
    'preciso' : ['precise', 'necessary'],
    'diverso' : ['different', 'several', 'diverse'],
    'familiar' : ['familiar', 'of the family'],
    'entero' : ['entire', 'whole', 'complete'],
    'interesante' : ['interesting'],
    'amplio' : ['wide', 'ample', 'broad'],
    'final' : 'final',
    'civil' : 'civil',
    'interno' : 'internal',
    'definitivo' : ['definitive', 'conclusive'],
    'perfecto' : 'perfect',
    'parecido' : 'similar',
    'raro' : ['strange', 'rare', 'scarce'],
    'particular' : ['particular', 'peculiar'],
    'militar' : 'military',
    'unido' : 'united',
    'extraordinario' : ['extraordinary', 'exceptional'],
    'verde' : 'green',
    'exacto' : ['exact', 'faithful', 'true'],
    'religioso' : 'religious',
    'oscuro' : ['dark', 'obscure'],
    'cuarto' : 'fourth',
    'azul' : 'blue',
    'frio' : 'cold',
    'concreto' : ['concrete', 'real'],
    'sencillo' : ['simple', 'plain', 'easy'],
    'derecho' : ['right', 'straight'],
    'determinado' : ['determined', 'fixed'],
    'perdido' : 'lost',
    'cercano' : 'near',
    'adecuado' : ['adequate', 'suitable'],
    'italiano' : 'Italian',
    'responsable' : 'responsible',
    'feliz' : ['happy', 'fortunate'],
    'aleman' : 'German',
    'dado' : 'given',
    'diario' : 'daily',
    'historico' : 'historical',
    'debido a' : 'due to',
    'minimo' : 'minimum'
}

adverb = {
    'no' : 'no',
    'ya' : ['already', 'still'],
    'muy' : ['very', 'really'],
    'tambien' : 'also',
    'asi' : 'like that',
    'si' : 'yes',
    'bien' : 'well',
    'entonces' : ['so', 'then'],
    'tan' : ['such', 'as', 'too', 'so'],
    'ahora' : 'now',
    'despues' : 'after',
    'siempre' : ['always', 'forever'],
    'solo' : ['only', 'just'],
    'antes' : 'before',
    'como' : 'how?',
    'aqui' : 'here',
    'luego' : ['later', 'afterwards'],
    'casi' : ['almost', 'nearly'],
    'durante' : 'during',
    'nunca' : ['never', 'ever'],
    'ademas' : ['also', 'as well', 'besides'],
    'hoy' : ['today', 'nowadays'],
    'alli' : 'there',
    'dentro' : 'inside',
    'ahi' : 'there',
    'todavia' : ['still', 'yet'],
    'tampoco' : ['neither', 'nor', 'either'],
    'aun' : ['still', 'yet'],
    'incluso' : ['including', 'even'],
    'quizas' : ['perhaps', 'maybe'],
    'mal' : 'badly',
    'alla' : 'there',
    'solamente' : 'only',
    'bueno' : 'well',
    'a traves' : ['across', 'over', 'through'],
    'junto' : ['together with', 'next to'],
    'cerca' : ['close', 'near'],
    'pronto' : ['soon', 'quick'],
    'realmente' : ['really', 'actually', 'in fact'],
    'donde' : 'where?',
    'encima' : ['above', 'on top', 'in addition'],
    'fuera' : ['out', 'outside', 'away'],
    'lejos' : 'far',
    'claro' : ['of course', 'clearly'],
    'atras' : ['back', 'behind', 'ago'],
    'adelante' : ['forward', 'further'],
    'arriba' : ['up', 'above'],
    'alrededor' : ['about', 'around', 'round'],
    'precisamente' : 'precisely',
    'apenas' : ['hardly', 'barely'],
    'simplemente' : ['simply', 'just'],
    'siquiera' : 'at least',
    'abajo' : ['down', 'below', 'downward'],
    'totalmente' : ['totally', 'completely'],
    'especialmente' : 'especially',
    'detras' : 'behind',
    'finalmente' : ['finally', 'at last'],
    'jamas' : 'never',
    'debajo' : ['underneath', 'below'],
    'aun' : ['even though', 'still'],
    'perfectamente' : 'perfectly',
    'recien' : ['recently', 'just'],
    'peor' : 'worse',
    'completamente' : 'completely',
    'inmediatamente' : 'immediately',
    'delante' : ['in front of', 'ahead'],
    'justo' : 'just',
    'salvo' : ['except for', 'but'],
    'directamente' : ['directly', 'straight away'],
    'probablemente' : 'probably',
    'exactamente' : 'exactly',
    'seguramente' : ['surely', 'securely']
}

noun = {
    'vez' : 'time',
    'ano' : 'year',
    'tiempo' : ['time', 'weather'],
    'dia' : 'day',
    'cosa' : 'thing',
    'hombre' : ['man', 'mankind', 'human'],
    'parte' : ['part', 'portion'],
    'vida' : 'life',
    'momento' : ['moment', 'time'],
    'forma' : ['form', 'shape', 'way'],
    'casa' : 'house',
    'mundo' : 'world',
    'mujer' : ['woman', 'wife'],
    'caso' : ['case', 'occasion'],
    'pais' : 'country',
    'lugar' : ['place', 'position'],
    'persona' : 'person',
    'hora' : ['hour', 'time'],
    'trabajo' : ['work', 'job', 'effort'],
    'punto' : ['point', 'dot', 'period'],
    'mano' : 'hand',
    'manera' : ['way', 'manner'],
    'fin' : 'end',
    'tipo' : ['type', 'kind'],
    'gente' : 'people',
    'ejemplo' : 'example',
    'lado' : 'side',
    'hijo' : ['son', 'chidren'],
    'problema' : 'problem',
    'cuenta' : ['bill', 'account'],
    'medio' : ['means', 'middle'],
    'pormedio' : 'through',
    'palabra' : 'word',
    'nino' : ['child', 'little boy'],
    'sin embargo' : 'nevertheless',
    'padre' : 'father',
    'cambio' : 'change',
    'historia' : ['history', 'story'],
    'idea' : 'idea',
    'agua' : 'water',
    'noche' : ['night', 'evening'],
    'ciudad' : 'city',
    'modo' : ['way', 'manner'],
    'nombre' : ['name', 'noun'],
    'familia' : 'family',
    'realidad' : ['reality', 'actuality'],
    'obra' : ['work', 'book', 'deed'],
    'verdad' : 'truth',
    'mes' : 'month',
    'razon' : 'reason',
    'tener razon' : 'to be right',
    'grupo' : 'group',
    'relacion' : ['relationship', 'relation'],
    'cuerpo' : 'body',
    'hecho' : ['fact', 'happening'],
    'principio' : ['beginning', 'principle'],
    'senor' : 'sir',
    'pueblo' : ['people', 'village'],
    'tarde' : ['afternoon', 'evening'],
    'ojo' : 'eye',
    'calle' : 'street',
    'libro' : 'book',
    'fuerza' : ['strength', 'force', 'power'],
    'luz' : 'light',
    'santo' : 'saint',
    'al frente' : 'facing',
    'frente a' : 'across from',
    'amigo' : 'friend',
    'sentido' : ['sense', 'feeling'],
    'paso' : ['step', 'pace'],
    'situacion' : 'situation',
    'gracias' : 'thank you',
    'siglo' : 'century',
    'dios' : 'god',
    'tierra' : ['earth', 'land', 'ground'],
    'papel' : ['paper', 'role', 'part'],
    'madre' : 'mother',
    'tema' : ['theme', 'subject', 'topic'],
    'clase' : ['kind', 'class', 'order'],
    'dinero' : 'money',
    'campo' : ['field', 'country'],
    'cabeza' : ['head'],
    'orden' : ['order', 'sequence'],
    'semana' : 'week',
    'al final' : ['finally', 'in the end'],
    'interes' : 'interest',
    'vista' : ['view', 'sight'],
    'acuerdo' : 'accord',
    'de acuerdo' : 'in agreement',
    'numero' : 'number',
    'fondo' : ['bottom', 'end'],
    'camino' : ['road', 'path', 'path'],
    'voz' : 'voice',
    'estudio' : ['study', 'learning'],
    'valor' : ['value', 'worth'],
    'medida' : 'measure',
    'a medida que' : 'to the extent',
    'centro' : ['center', 'middle', 'downtown'],
    'necesidad' : ['necessity', 'need'],
    'condicion' : 'condition',
    'falta' : ['lack', 'shortage'],
    'edad' : 'age',
    'estado' : ['state', 'condition', 'status'],
    'ser' : 'being',
    'puerta' : 'door',
    'cara' : ['face', 'expression'],
    'epoca' : ['time', 'age', 'period'],
    'color' : 'color',
    'experiencia' : 'experience',
    'movimiento' : 'movement',
    'pesar' : 'sorrow',
    'a pesar de' : 'in spite of',
    'posibilidad' : 'possibility',
    'juego' : ['game', 'play', 'sport'],
    'aire' : ['air', 'wind', 'appearance'],
    'guerra' : 'war',
    'resultado' : ['result', 'outcome'],
    'ley' : ['law', 'bill', 'rule'],
    'aspecto' : ['aspect', 'appearance'],
    'pie' : ['foot', 'base'],
}
