# source: https://senorasenora.files.wordpress.com/2018/09/a_frequency_dictionary_of_spanish.pdf

# fuction words, all inc regardless of freq

article = {
    'el' : 'the',
    'la' : 'the',
    'un' : ['a', 'an']
}

conjunction = {
    'que' : ['that', 'which'],
    'y' : 'and',
    'como' : ['like', 'as'],
    'pero' : ['but', 'yet', 'except'],
    'o' : 'or',
    'si' : ['if', 'whether'],
    'porque' : 'because',
    'cuando' : 'when',
    'ni' : ['not even', 'neither', 'nor'],
	 'donde' : 'where',
	 'pues' : ['then', 'well then'],
	 'sino' : ['but', 'except', 'rather'],
	 'aunque' : ['although', 'even though'],
	 'mientras' : ['while', 'whereas', 'as long as'],
	 'mas' : ['but', 'however']
}

interjection = {
	'ah' : 'oh',
	'ay' : ['oh no!', 'oh my!'],
	'eh' : 'eh',
	'oh' : 'oh',
	'hola' : ['hello', 'hi']
}

preposition = {
	'de' : ['of', 'from'],
	'a' : ['to', 'at'],
	'en' : ['in', 'on'],
	'por' : ['by', 'for', 'through'],
	'con' : 'with',
	'para' : ['for', 'to', 'in order to'],
	'sin' : 'without',
	'sobre' : ['on top of', 'over', 'about'],
	'hasta' : ['until', 'up to', 'even'],
	'entre' : ['between', 'among'],
	'desde' : ['from', 'since'],
	'hacia' : ['toward', 'towards'],
	'contra' : ['against', 'opposite'],
	'bajo' : ['under', 'underneath'],
	'ante' : ['before', 'in the presence of'],
	'segun' : 'according to',
	'tras' : ['after', 'behind'],
	'mediante' : 'by means of',
	'excepto' : 'except'
}

number = {
	'cero' : ['zero', 'naught', 'nil'],
	'uno' : 'one',
	'dos' : 'two',
	'tres' : 'three',
	'cuatro' : 'four',
	'cinco' : 'five',
	'seis' : 'six',
	'siete' : 'seven',
	'ocho' : 'eight',
	'nueve' : 'nine',
	'diez' : 'ten',
	'once' : 'eleven',
	'doce' : 'twelve',
	'trece' : 'thirteen',
	'catorce' : 'fourteen',
	'quince' : 'fifteen',
	'dieciseis' : 'sixteen',
	'de diecisiete' : 'seventeen',
	'dieciocho' : 'eighteen',
	'diecinueve' : 'nineteen',
	'veinte' : 'twenty',
	'veintiuno' : 'twenty one',
	'veintidos': 'twenty two',
	'veintitres' : 'twenty three',
	'treinta' : 'thirty',
	'treinta y uno' : 'thirty one',
	'treinta y dos' : 'thirty two',
	'treinta y tres' : 'thirty three',
	'cuarenta' : 'fourty',
	'cincuenta' : 'fifty',
	'sesenta' : 'sixty',
	'setenta' : 'seventy',
	'ochenta' : 'eighty',
	'noventa' : 'ninety',
	'cien' : 'hundred',
	'ciento diez' : 'hundred ten',
	'ciento veintidos' : 'hundred twenty two',
	'ciento treinta y tres' : 'hundred thirty three',
	'doscientos' : 'two hundred',
	'trescientos' : 'three hundred',
	'mil' : 'thousand',
	'mil cien' : 'thousand hundred',
	'mil docientos' : 'thousand two hundred',
	'mil trescientos' : 'thousand three hundred',
	'diez mil' : 'ten thousand',
	'veinte mil' : 'twenty thousand',
	'treinta mil' : 'thirty thousand',
	'cien mil' : 'hundred thousand',
	'doscientos mil' : 'two hundred thousand',
	'trescientos mil' : 'three hundred thousand',
	'millon' : 'million',
	'dos millones' : 'two million',
	'tres millones' : 'three million',
	'diez millones' : 'ten million',
	'viente millones' : 'twenty million',
	'treinta millones' : 'thirty million',
	'cien millones' : 'hundred million',
	'mil millones' : 'billion',
	'cien mil millones' : 'hundred billion'
}

pronoun = {
	'se' : 'be',
	'me' : 'me',
	'te' : 'you',
	'lo' : 'him',
	'la' : 'her',
	'le' : ['to him', 'to her'],
	'nos' : 'us',
	'les' : 'you all',
	'los' : 'them',
	'las' : 'them',
	'les' : 'to them',
	'el' : 'he',
	'que' : ['what?', 'which?', 'how!'],
	'yo' : 'I',
	'eso' : 'that',
	'ella' : 'she',
	'nada' : 'nothing',
	'algo' : ['something', 'somewhat'],
	'esto' : 'this',
	'quien' : ['who', 'whom'],
	'cual' : ['which', 'who', 'whom'],
	'este' : 'this one',
	'nosotros' : 'we',
	'nadie' : ['nobody', 'anybody'],
	'usted' : 'you',
	'quien' : ['who?', 'whom?'],
	'ello' : 'it',
	'mi' : 'me',
	'cual' : 'which?',
	'alguien' : ['somebody', 'someone', 'anyone'],
	'suyo' : ['his', 'hers', 'yours', 'theirs'],
	'tu' : 'you',
	'aquello' : 'that over there',
	'ese' : 'that one',
	'mio' : 'mine',
	'os' : 'you',
	'aquel' : 'that one over there',
	'ti' : 'you',
	'conmigo' : 'with me',
	'tuyo' : 'yours',
	'contigo' : 'with you',
	'vos' : 'you',
	'vosotros' : 'you'
}

# lexical words, only if freq < 1k

adjective = {
	'su' : ['his', 'her', 'their', 'your'],
	'lo' : 'the',
	'todo' : ['all', 'every'],
	'mas' : 'more',
	'este' : 'this',
	'otro' : ['other', 'another'],
	'ese' : 'that',
	'mucho' : ['much', 'many', 'a lot'],
	'mi' : 'my',
	'alguno' : ['some', 'someone'],
	'mismo' : 'same',
	'primero' : 'first',
	'grande' : ['large', 'great', 'big'],
	'poco' : ['little', 'few', 'a little bit'],
	'tanto' : ['so much', 'so many'],
	'neustro' : 'our',
	'cada' : ['each', 'every'],
	'menos' : ['less', 'fewer'],
	'nuevo' : 'new',
	'aquel' : 'that',
	'bueno' : 'good',
	'tal' : 'such',
	'mejor' : ['best', 'better'],
	'cierto' : ['certain', 'sure', 'true'],
	'mayor' : ['larger', 'older', 'main'],
	'ultimo' : ['last', 'final'],
	'propio' : ['own', 'proper', 'typical'],
	'ninguno' : ['no', 'none', 'nobody'],
    'cualquier' : ['any', 'anyone'],
    'solo' : ['lonely', 'alone'],
    'largo' : 'long',
    'unico' : ['only', 'unique', 'sole'],
    'peqeno' : ['little', 'small', 'young'],
    'alto' : ['tall', 'high'],
    'importante' : 'important',
    'medio' : ['half', 'middle'],
    'cuanto' : 'regarding',
    'humano' : 'human',
    'varios' : ['severa', 'various'],
    'posible' : 'possible',
    'general' : 'general',
    'igual' : ['equal', 'same'],
    'segundo' : 'second',
    'blanco' : 'white',
    'distinto' : ['distinct', 'different'],
    'claro' : 'clear',
    'cuyo' : 'whose',
    'bastante' : ['rather', 'fairly', 'quite a bit'],
    'malo' : 'bad',
    'social' : 'social',
    'viejo' : ['old', 'aged'],
    'politico' : 'political',
    'espanol' : 'Spanish',
    'siguiente' : ['following', 'next'],
    'demas' : ['the rset', 'others'],
    'dificil' : ['difficult', 'hard'],
    'negro' : 'black',
    'necesario' : 'necessary',
    'menor' : ['younger', 'youngest'],
    'demasiado' : ['too much', 'too many'],
    'antiguo' : ['old', 'ancient', 'former'],
    'tu' : 'your',
    'especial' : 'special',
    'diferente' : ['different', 'separate'],
    'anterior' : ['previous', 'preceding'],
    'pobre' : 'poor',
    'tercero' : 'third',
    'capaz' : ['capable', 'able'],
    'bajo': ['short', 'low'],
    'libre' : ['free', 'vacant'],
    'natural' : 'natural',
    'verdadero' : ['true', 'real'],
    'economico' : 'economic',
    'comun' : 'common',
    'abierto' : ['open', 'unlocked'],
    'proximo' : 'next',
    'joven' : 'young',
    'pasado' : ['past', 'last'],
    'vivo' : ['alive', 'bright'],
    'completo' : 'complete',
    'contrario' : ['contrary', 'opposite'],
    'real' : ['royal', 'real', 'authentic'],
    'publico' : 'public',
    'enorme' : ['enormous', 'vast'],
    'ambos' : 'both',
    'profundo' : ['deep', 'profound'],
    'principal' : ['main', 'principal'],
    'nacional' : 'national',
    'lleno' : ['full', 'filled'],
    'supuesto' : ['supposed'],
    'por supuesto' : 'of course',
    'facil' : 'easy',
    'rojo' : 'red',
    'superior' : ['superior', 'upper'],
    'corto' : ['short', 'brief'],
    'conocido' : ['known', 'well known'],
    'serio' : 'serious',
    'suficiente' : ['sufficient', 'enough'],
    'grave' : ['serious', 'solemn'],
    'extrano' : ['strange', 'foreign'],
    'absoluto' : 'absolute',
    'personal' : 'peronal',
    'imposible' : 'impossible',
    'ingles' : 'English',
    'duro' : 'hard',
    'rico' : ['rich', 'tasty'],
    'total' : ['total', 'entire'],
    'puro' : ['pure', 'clean'],
    'profesional' : 'professional',
    'fisico' : 'physical',
    'frances' : 'French',
    'rapido' : ['quick', 'fast'],
    'simple' : ['simple', 'mere', 'simple minded'],
    'normal' : ['normal', 'usual', 'regular'],
    'moderno' : 'modern',
    'actual' : 'current',
    'pleno' : ['complete', 'full'],
    'cerrado' : 'closed',
    'muerto' : 'dead',
    'dispuesto' : ['willing', 'ready'],
    'enfermo' : ['ill', 'sick'],
    'privado' : 'private',
    'popular' : 'popular',
    'famoso' : ['famous', 'well known'],
    'cuanto' : 'how much?',
    'inmediato' : 'immediate',
    'junto' : 'together',
    'directo' : ['direct', 'straight'],
    'preciso' : ['precise', 'necessary'],
    'diverso' : ['different', 'several', 'diverse'],
    'familiar' : ['familiar', 'of the family'],
    'entero' : ['entire', 'whole', 'complete'],
    'interesante' : ['interesting'],
    'amplio' : ['wide', 'ample', 'broad'],
    'final' : 'final',
    'civil' : 'civil',
    'interno' : 'internal',
    'definitivo' : ['definitive', 'conclusive'],
    'perfecto' : 'perfect',
    'parecido' : 'similar',
    'raro' : ['strange', 'rare', 'scarce'],
    'particular' : ['particular', 'peculiar'],
    'militar' : 'military',
    'unido' : 'united',
    'extraordinario' : ['extraordinary', 'exceptional'],
    'verde' : 'green',
    'exacto' : ['exact', 'faithful', 'true'],
    'religioso' : 'religious',
    'oscuro' : ['dark', 'obscure'],
    'cuarto' : 'fourth',
    'azul' : 'blue',
    'frio' : 'cold',
    'concreto' : ['concrete', 'real'],
    'sencillo' : ['simple', 'plain', 'easy'],
    'derecho' : ['right', 'straight'],
    'determinado' : ['determined', 'fixed'],
    'perdido' : 'lost',
    'cercano' : 'near',
    'adecuado' : ['adequate', 'suitable'],
    'italiano' : 'Italian',
    'responsable' : 'responsible',
    'feliz' : ['happy', 'fortunate'],
    'aleman' : 'German',
    'dado' : 'given',
    'diario' : 'daily',
    'historico' : 'historical',
    'debido a' : 'due to',
    'minimo' : 'minimum'
}

adverb = {
    'no' : 'no',
    'ya' : ['already', 'still'],
    'muy' : ['very', 'really'],
    'tambien' : 'also',
    'asi' : 'like that',
    'si' : 'yes',
    'bien' : 'well',
    'entonces' : ['so', 'then'],
    'tan' : ['such', 'as', 'too', 'so'],
    'ahora' : 'now',
    'despues' : 'after',
    'siempre' : ['always', 'forever'],
    'solo' : ['only', 'just'],
    'antes' : 'before',
    'como' : 'how?',
    'aqui' : 'here',
    'luego' : ['later', 'afterwards'],
    'casi' : ['almost', 'nearly'],
    'durante' : 'during',
    'nunca' : ['never', 'ever'],
    'ademas' : ['also', 'as well', 'besides'],
    'hoy' : ['today', 'nowadays'],
    'alli' : 'there',
    'dentro' : 'inside',
    'ahi' : 'there',
    'todavia' : ['still', 'yet'],
    'tampoco' : ['neither', 'nor', 'either'],
    'aun' : ['still', 'yet'],
    'incluso' : ['including', 'even'],
    'quizas' : ['perhaps', 'maybe'],
    'mal' : 'badly',
    'alla' : 'there',
    'solamente' : 'only',
    'bueno' : 'well',
    'a traves' : ['across', 'over', 'through'],
    'junto' : ['together with', 'next to'],
    'cerca' : ['close', 'near'],
    'pronto' : ['soon', 'quick'],
    'realmente' : ['really', 'actually', 'in fact'],
    'donde' : 'where?',
    'encima' : ['above', 'on top', 'in addition'],
    'fuera' : ['out', 'outside', 'away'],
    'lejos' : 'far',
    'claro' : ['of course', 'clearly'],
    'atras' : ['back', 'behind', 'ago'],
    'adelante' : ['forward', 'further'],
    'arriba' : ['up', 'above'],
    'alrededor' : ['about', 'around', 'round'],
    'precisamente' : 'precisely',
    'apenas' : ['hardly', 'barely'],
    'simplemente' : ['simply', 'just'],
    'siquiera' : 'at least',
    'abajo' : ['down', 'below', 'downward'],
    'totalmente' : ['totally', 'completely'],
    'especialmente' : 'especially',
    'detras' : 'behind',
    'finalmente' : ['finally', 'at last'],
    'jamas' : 'never',
    'debajo' : ['underneath', 'below'],
    'aun' : ['even though', 'still'],
    'perfectamente' : 'perfectly',
    'recien' : ['recently', 'just'],
    'peor' : 'worse',
    'completamente' : 'completely',
    'inmediatamente' : 'immediately',
    'delante' : ['in front of', 'ahead'],
    'justo' : 'just',
    'salvo' : ['except for', 'but'],
    'directamente' : ['directly', 'straight away'],
    'probablemente' : 'probably',
    'exactamente' : 'exactly',
    'seguramente' : ['surely', 'securely']
}

noun = {
    'vez' : 'time',
    'ano' : 'year',
    'tiempo' : ['time', 'weather'],
    'dia' : 'day',
    'cosa' : 'thing',
    'hombre' : ['man', 'mankind', 'human'],
    'parte' : ['part', 'portion'],
    'vida' : 'life',
    'momento' : ['moment', 'time'],
    'forma' : ['form', 'shape', 'way'],
    'casa' : 'house',
    'mundo' : 'world',
    'mujer' : ['woman', 'wife'],
    'caso' : ['case', 'occasion'],
    'pais' : 'country',
    'lugar' : ['place', 'position'],
    'persona' : 'person',
    'hora' : ['hour', 'time'],
    'trabajo' : ['work', 'job', 'effort'],
    'punto' : ['point', 'dot', 'period'],
    'mano' : 'hand',
    'manera' : ['way', 'manner'],
    'fin' : 'end',
    'tipo' : ['type', 'kind'],
    'gente' : 'people',
    'ejemplo' : 'example',
    'lado' : 'side',
    'hijo' : ['son', 'chidren'],
    'problema' : 'problem',
    'cuenta' : ['bill', 'account'],
    'medio' : ['means', 'middle'],
    'pormedio' : 'through',
    'palabra' : 'word',
    'nino' : ['child', 'little boy'],
    'sin embargo' : 'nevertheless',
    'padre' : 'father',
    'cambio' : 'change',
    'historia' : ['history', 'story'],
    'idea' : 'idea',
    'agua' : 'water',
    'noche' : ['night', 'evening'],
    'ciudad' : 'city',
    'modo' : ['way', 'manner'],
    'nombre' : ['name', 'noun'],
    'familia' : 'family',
    'realidad' : ['reality', 'actuality'],
    'obra' : ['work', 'book', 'deed'],
    'verdad' : 'truth',
    'mes' : 'month',
    'razon' : 'reason',
    'tener razon' : 'to be right',
    'grupo' : 'group',
    'relacion' : ['relationship', 'relation'],
    'cuerpo' : 'body',
    'hecho' : ['fact', 'happening'],
    'principio' : ['beginning', 'principle'],
    'senor' : 'sir',
    'pueblo' : ['people', 'village'],
    'tarde' : ['afternoon', 'evening'],
    'ojo' : 'eye',
    'calle' : 'street',
    'libro' : 'book',
    'fuerza' : ['strength', 'force', 'power'],
    'luz' : 'light',
    'santo' : 'saint',
    'al frente' : 'facing',
    'frente a' : 'across from',
    'amigo' : 'friend',
    'sentido' : ['sense', 'feeling'],
    'paso' : ['step', 'pace'],
    'situacion' : 'situation',
    'gracias' : 'thank you',
    'siglo' : 'century',
    'dios' : 'god',
    'tierra' : ['earth', 'land', 'ground'],
    'papel' : ['paper', 'role', 'part'],
    'madre' : 'mother',
    'tema' : ['theme', 'subject', 'topic'],
    'clase' : ['kind', 'class', 'order'],
    'dinero' : 'money',
    'campo' : ['field', 'country'],
    'cabeza' : ['head'],
    'orden' : ['order', 'sequence'],
    'semana' : 'week',
    'al final' : ['finally', 'in the end'],
    'interes' : 'interest',
    'vista' : ['view', 'sight'],
    'acuerdo' : 'accord',
    'de acuerdo' : 'in agreement',
    'numero' : 'number',
    'fondo' : ['bottom', 'end'],
    'camino' : ['road', 'path', 'path'],
    'voz' : 'voice',
    'estudio' : ['study', 'learning'],
    'valor' : ['value', 'worth'],
    'medida' : 'measure',
    'a medida que' : 'to the extent',
    'centro' : ['center', 'middle', 'downtown'],
    'necesidad' : ['necessity', 'need'],
    'condicion' : 'condition',
    'falta' : ['lack', 'shortage'],
    'edad' : 'age',
    'estado' : ['state', 'condition', 'status'],
    'ser' : 'being',
    'puerta' : 'door',
    'cara' : ['face', 'expression'],
    'epoca' : ['time', 'age', 'period'],
    'color' : 'color',
    'experiencia' : 'experience',
    'movimiento' : 'movement',
    'pesar' : 'sorrow',
    'a pesar de' : 'in spite of',
    'posibilidad' : 'possibility',
    'juego' : ['game', 'play', 'sport'],
    'aire' : ['air', 'wind', 'appearance'],
    'guerra' : 'war',
    'resultado' : ['result', 'outcome'],
    'ley' : ['law', 'bill', 'rule'],
    'aspecto' : ['aspect', 'appearance'],
    'pie' : ['foot', 'base'],
    'especie' : ['kind', 'sort', 'species'],
    'servicio' : ['service', 'helpfulness'],
    'actividad' : ['activity', 'action'],
    'cuestion' : ['question', 'matter'],
    'duda' : 'doubt',
    'diferencia' : 'difference',
    'manana' : ['morning', 'tomorrow'],
    'cantidad' : ['quantity', 'amount'],
    'accion' : ['action', 'act', 'deed'],
    'sociedad' : 'society',
    'peso' : ['Peso', 'weight', 'load'],
    'efecto' : 'effect',
    'objecto' : ['object', 'thing'],
    'amor' : 'love',
    'muerte' : 'death',
    'partido' : ['party', 'group', 'match'],
    'derecho' : ['right', 'justice', 'law'],
    'poder' : 'power',
    'importancia' : 'importance',
    'sistema' : 'system',
    'viaje' : ['travel', 'trip'],
    'suelo' : ['ground', 'floor'],
    'respecto' : 'respect',
    'con respecto a' : 'with regards to',
    'conocimiento' : 'knowledge',
    'libertad' : ['freedom', 'liberty'],
    'atencion' : 'attention',
    'esfuerzo' : ['effort', 'endeavor'],
    'resto' : ['rest', 'remainder', 'leftover'],
    'zona' : ['area', 'zone'],
    'miedo' : 'fear',
    'proceso' : ['process', 'procedure'],
    'minuto' : 'minute',
    'mesa' : ['table', 'board'],
    'ocasion' : ['opportunity', 'occasion'],
    'programa' : ['program', 'plan'],
    'favor' : ['favor', 'benefit'],
    'respuesta' : ['answer', 'reply'],
    'linea' : ['line', 'course'],
    'espacio' : ['space', 'room'],
    'nivel' : 'level',
    'gobierno' : 'governmnet',
    'cabo' : ['end', 'bit'],
    'llevar a cabo' : 'to carry out',
    'pregunta' : 'question',
    'imagen' : ['image', 'picture'],
    'carrera' : ['career', 'course', 'race'],
    'figura' : 'figure',
    'animal' : 'animal',
    'base' : 'base',
    'posicion' : 'position',
    'motivo' : ['motive', 'cause'],
    'prueba' : ['proof', 'trail', 'test'],
    'politica' : ['politics', 'policy'],
    'dato' : 'data',
    'empresa' : ['firm', 'company', 'venture'],
    'asunto' : ['matter', 'issue', 'affair'],
    'presencia' : ['presence', 'appearance'],
    'cultura' : 'culture',
    'serie' : 'series',
    'caracter' : ['personality', 'nautre'],
    'mayoria' : 'majority',
    'escuela' : 'school',
    'autor' : 'author',
    'hermano' : 'brother',
    'funcion' : ['function', 'meeting'],
    'causa' : 'cause',
    'decision' : 'decision',
    'musica' : 'music',
    'expresion' : 'expression',
    'rio' : 'river',
    'seguridad' : ['security', 'safety'],
    'termino' : ['term', 'end'],
    'metro' : ['meter', 'subway'],
    'medico' : 'doctor',
    'arte' : 'art',
    'consecuencia' : 'consequence',
    'acto' : 'act',
    'pena' : 'trouble',
    'valer la pena' : 'be of worth',
    'segundo' : 'second',
    'altura' : 'height',
    'deseo' : 'desire',
    'joven' : 'teenager',
    'sueno' : ['dream', 'sleep'],
    'tarea' : 'task',
    'carta' : ['letter', 'playing card'],
    'propiedad' : 'property',
    'producto' : 'product',
    'gusto' : ['pleasure', 'taste', 'preference'],
    'ayuda' : 'help',
    'lengua' : ['language', 'tongue'],
    'plan' : 'plan',
    'vuelta' : ['return', 'turn'],
    'proyecto' : ['project', 'plan'],
    'memoria' : 'memory',
    'origen' : 'origin',
    'elemento' : 'element',
    'mercado' : 'market',
    'curso' : ['course', 'direction'],
    'sangre' : 'blood',
    'interior' : 'interior',
    'uso' : 'use',
    'brazo' : 'arm',
    'profesor' : 'professor',
    'futuro' : 'future',
    'oportunidad' : 'opportunity',
    'mitad' : ['half', 'middle'],
    'recuerdo' : 'memory',
    'opinion' : 'opinion',
    'boca' : ['mouth', 'entrance', 'opening'],
    'direccion' : 'direction',
    'pieza' : 'piece',
    'actitud' : 'attitude',
    'mar' : 'sea',
    'entrada' : 'entrance',
    'contacto' : 'contact',
    'corazon' : 'heart',
    'capital' : 'capital',
    'titulo' : 'title',
    'cuarto' : 'room',
    'material' : 'material',
    'golpe' : ['hit', 'strile', 'punch'],
    'comunicacion' : 'communication',
    'enfermedad' : 'illness',
    'bien' : ['goods', 'property'],
    'materia' : ['matter', 'subject'],
    'sitio' : ['place', 'space'],
    'naturaleza' : ['nature', 'character'],
    'capacidad' : 'capacity',
    'distancia' : 'distance',
    'informacion' : 'information',
    'ambiente' : ['environment', 'atmosphere'],
    'desarrollo' : 'development',
    'sol' : 'sun',
    'companero' : ['companion', 'classmate'],
    'salida' : ['exit', 'escape', 'outcome'],
    'conciencia' : ['conscience' , 'consciousness'],
    'costumbre' : ['habit', 'custom', 'usage'],
    'paz' : 'peace',
    'noticia' : 'news',
    'circunstancia' : 'circumstance',
    'dolor' : ['pain', 'ache', 'sorrow'],
    'estilo' : 'styel',
    'precio' : ['price', 'cost', 'value'],
    'planta' : ['plant', 'floor'],
    'personaje' : 'character',
    'exito' : 'success',
    'hija' : 'daughter', 
    'edificio' : 'building',
    'autoridad' : 'authority',
    'piedra' : ['stone', 'rock'],
    'conjunto' : ['group', 'set'],
    'suerte' : ['luck', 'fortune'],
    'espiritu' : ['spirit', 'ghost'],
    'miembro' : ['member', 'limb'],
    'recurso' : ['resource', 'recourse', 'means'],
    'pared' : 'wall',
    'equipo' : ['team', 'equipment', 'outfit'],
    'error' : ['error', 'mistake'],
    'dificultad' : ['difficulty', 'obstacle'],
    'voluntad' : ['will', 'willpower', 'intention'],
    'reunion' : ['meeting', 'reunion'],
    'modelo' : ['model', 'pattern'],
    'fecha' : ['date', 'day'],
    'proposito' : ['intention', 'purpose'],
    'cuidado' : ['care', 'carefulness'],
    'puesto' : ['job', 'place', 'position'],
    'grado' : ['degree', 'grade'],
    'lucha' : ['fight', 'struggle', 'wrestle'],
    'jefe' : ['leader', 'boss', 'manager'],
    'periodico' : ['newspaper', 'periodical'],
    'par' : ['pair', 'couple', 'a la par', 'at the same time'],
    'publico' : ['public', 'audience'],
    'calidad' : 'quality',
    'ciencia' : ['science', 'knowledge'],
    'tamano' : ['size', 'dimension'],
    'doctor' : 'doctor', 
    'cuadro' : ['painting', 'picture'],
    'caballo' : 'horse',
    'responsabilidad' : 'responsibility',
    'detalle' : 'detail',
    'marcha' : ['march', 'progress'],
    'carne' : ['meant', 'flesh'],
    'pensamiento' : ['thought', 'thinking'],
    'cargo' : ['position', 'charge', 'fee'],
    'santa' : 'saint',
    'construccion' : 'construction',
    'juicio' : 'judgement',
    'terreno' : ['ground', 'earth', 'terrain'],
    'piso' : ['floor', 'storey'],
    'compania' : 'company',
    'texto' : 'text',
    'fuente' : ['source', 'fountain'],
    'presente' : 'present',
    'revista' : ['magazine', 'journal'],
    'esperanza' : 'hope',
    'maquina' : 'machine', 
    'frase' : 'phrase',
    'sala' : ['room', 'hall'],
    'instrumento' : 'instrument',
    'defensa' : ['defense', 'plea'],
    'director' : ['director', 'manager', 'principal'],
    'explicacion' : 'explanation',
    'articulo' : ['article', 'product', 'item'],
    'radio' : ['radio', 'set', 'communication'],
    'pelicula' : ['movie', 'film'],
    'eleccion' : ['election', 'choice'],
    'visita' : ['visit', 'visitor', 'guest'],
    'apoyo' : ['support', 'backing'],
    'presidente' : 'president',
    'arma' : 'weapon',
    'encuentro' : ['meeting', 'game' , 'skirmish'],
    'corriente' : ['current', 'flow'],
    'lectura' : 'reading',
    'existencia' : ['existence', 'life'],
    'lenguaje' : ['language', 'speech'],
    'destino' : ['destination', 'destiny'],
    'educacion' : 'education',
    'operacion' : 'operation',
    'nota' : ['note', 'grade'],
    'teatro' : ['theater', 'drama'],
    'negocio' : ['business', 'transaction'],
    'letra' : ['letter', 'handwriting', 'lyrics'],
    'sentimiento' : ['feeling', 'sentiment'],
    'solucion' : ['solution', 'answer'],
    'comida' : ['food', 'meal'],
    'impresion' : ['impression', 'printing'],
    'plano' : ['plane', 'map', 'level'],
    'intencion' : 'intention',
    'ritmo' : 'rhythm', 
    'banco' : ['bank', 'bench'],
    'piel': ['skin', 'hide', 'fur'],
    'control' : 'control',
    'investigacion' : 'investigation',
    'conversacion' : 'conversation',
    'verano' : 'summer',
    'respeto' : ['respect', 'guard'],
    'norte' : 'north',
    'tradicion' : 'tradition',
    'poblacion' : 'population',
    'pareja' : ['couple', 'pair'],
    'pasado' : 'past',
    'diario' : 'newspaper',
    'generacion' : 'generation', 
    'vision' : 'vision',
    'peligro' : ['danger', 'menace'],
    'oro' : 'gold', 
    'vino' : 'wine',
    'etapa' : ['stage', 'period'],
    'silencio' : 'silence',
    'artista' : ['artist', 'performer'],
    'labor' : ['labor', 'work', 'task'],
    'cielo' : ['sky', 'heaven', 'ceiling'],
    'practica' : ['practice', 'skill'],
    'limite' : 'limit', 
    'masa' : ['mass', 'dough', 'bulk', 'crowd'],
    'formacion' : ['formation', 'education'],
    'perro' : 'dog',
    'izquierda' : 'left',
    'energia' : ['energy', 'power'],
    'confianza' : ['confidence', 'trust'],
    'flor' : 'flower',
    'esposa' : 'wife',
    'revolucion' : 'revolution',
    'maestro' : ['teacher', 'master'],
    'fenomeno' : 'phenomenon',
    'presion' : 'pressure',
    'alumno' : ['student', 'pupil'],
    'teoria' : 'theory',
    'tono' : 'tone',
    'salud' : 'health',
    'senora': ['mrs.', 'lady', 'madam'],
    'via' : ['road', 'way'],
    'alma' : 'soul',
    'madera' : 'wood', 
    'fiesta' : ['party', 'feast'],
    'calor' : ['heat', 'warmth'] ,
    'hogar' : ['home', 'hearth'],
    'mente' : 'mind',
    'preocupacion' : ['worry', 'concern'],
    'concepto' : 'concept',
    'telefono' : ['phone', 'telephone']
}

verb = {
    'ser' : 'to be',
    'haber' : 'to have',
    'estar' : 'to be',
    'tener' : 'to have',
    'hacer' : 'to do',
    'poder' : ['to be able to', 'can'],
    'decir' : ['to tell', 'say'],
    'ir' : 'to go',
    'ver' : 'to see',
    'dar' : 'to give birth',
    'saber' : ['to know', 'find out'],
    'querer' : ['to want', 'love'],
    'llegar' : 'to arrive',
    'pasar' : ['to pass', 'spend'],
    'deber' : ['should', 'ought to', 'to owe'],
    'poner' : ['to put', 'get'],
    'parecer' : ['to seem', 'look alike'],
    'quedar' : ['to remain', 'stay'],
    'creer' : ['to believe', 'think'],
    'hablar' : ['to speak', 'talk'],
    'llevar' : ['to take', 'carry'],
    'dejar' : ['to let', 'leave'],
    'seguir' : ['to follow', 'keep on'],
    'encontrar' : 'to find',
    'llamar' : ['to call', 'name'],
    'venir' : 'to come',
    'pensar' : 'to think',
    'salir' : ['to leave', 'go out'],
    'volver' : 'to return',
    'tomar' : ['to take', 'drink'],
    'conocer' : 'to know',
    'vivir' : 'to live',
    'sentir' : ['to feel', 'regret'],
    'tratar' : ['to try', 'treat', 'deal with'],
    'mirar' : ['to look', 'watch'],
    'contar' : ['to tell', 'count'],
    'empezar' : ['to begin', 'start'],
    'esperar' : ['to wait', 'hope', 'expect'],
    'buscar' : 'to look for',
    'existir' : 'to exist',
    'entrar' : 'to enter',
    'trabajar' : 'to work',
    'escribir' : 'to write',
    'perder' : ['to lose', 'miss'],
    'producir' : ['to produce', 'cause'],
    'ocurrir' : ['to happen', 'occur'],
    'entender' : 'to understand',
    'pedir' : ['to ask for', 'request'],
    'recibir' : 'to receive',
    'recordar' : ['to remember', 'remind'],
    'terminar' : ['to finish', 'end'],
    'permitir' : ['to allow', 'permit'],
    'aparecer' : 'to appear',
    'conseguir' : ['to get', 'to acquire', 'obtain'],
    'comenzar' : ['to begin', 'start'],
    'servir' : 'to serve',
    'sacar' : 'to take out',
    'necesitar' : 'to need',
    'mantener' : ['to keep', 'maintain'],
    'resultar' : ['to result', 'turn out'],
    'leer' : 'to read',
    'caer' : 'to fall', 
    'cambiar' : 'to change',
    'presentar' : ['to introduce', 'present'],
    'crear' : 'to create',
    'abrir' : 'to open',
    'considerar' : 'to consider',
    'oir' : 'to hear',
    'acabar' : 'finish',
    'convertir' : ['to convert', 'change', 'become'],
    'ganar' : ['to win', 'earn'],
    'formar' : 'to form',
    'traer' : ['to bring', 'carry'],
    'partir' : ['to divide', 'leave'],
    'morir' : 'to die',
    'aceptar' : 'to accept',
    'realizar' : ['to fulfill', 'carry out'],
    'suponer' : ['to suppose', 'assume'],
    'comprender' : 'to understand',
    'logar' : ['to achieve', 'get', 'manage'],
    'explicar' : 'to explain',
    'preguntar' : 'to ask',
    'tocar' : ['to touch', 'play'],
    'reconocer' : ['to recognize', 'admit'],
    'estudiar' : 'to study',
    'alcanzar' : ['to reach', 'catch up with'],
    'nacer' : 'to be born',
    'dirigir' : ['to direct', 'manage'],
    'correr' : 'to run',
    'utilizar' : ['to use', 'utilize'],
    'pagar' : 'to pay',
    'ayudar' : 'to help',
    'gustar' : 'to be pleasing to',
    'jugar' : 'to play',
    'escuchar' : 'to listen to',
    'cumplir' : 'to fulfill',
    'ofrecer': ['to offer', 'present'],
    'descubrir' : 'to discover',
    'levantar' : ['to raise', 'lift'],
    'intentar' : ['to try', 'attempt'],
    'usar' : 'to use',
    'decidir' : 'to decide',
    'repetir' : 'to repeat',
    'olvidar' : 'to forget',
    'valer' : ['to be worth', 'cost'],
    'comer' : 'to eat',
    'mostrar' : 'to show',
    'ocupar' : ['to occupy', 'use'],
    'mover' : ['to move', 'incite'],
    'continuar' : 'to continue',
    'suceder' : 'to happen',
    'fijar' : ['to set', 'fix'],
    'referir' : 'to refer',
    'acercar' : 'to come near',
    'dedicar' : ['to dedicate', 'devote'],
    'aprender' : 'to learn',
    'comprar' : 'to buy',
    'subir' : 'to go up',
    'evitar' : ['to avoid', 'prevent'],
    'interesar' : 'to interest',
    'cerrar' : 'to close',
    'echar' : ['to throw', 'cast'],
    'responder' : ['to answer', 'respond'],
    'sufrir' : ['to suffer', 'undergo'],
    'importar' : ['to matter', 'import'],
    'obtener' :' to obtain',
    'observar' : 'to observe',
    'indicar' : 'to indicate',
    'imaginar' :  'to imagine',
    'soler' : 'to be accustomed to',
    'detener' : ['to stop', 'detain'],
    'desarrollar' : 'to develop',
    'senalar' : ['to point', 'signal'],
    'elegir' : ['to choose', 'elect'],
    'preparar' : 'to prepare',
    'proponer' : 'to propose',
    'demonstrar' : ['to show', 'demonstrate'],
    'significar' : 'to mean',
    'reunir' : ['to gather', 'meet', 'collect'],
    'faltar' : 'to be lacking',
    'acompanar' : 'to accompany',
    'desear' : ['to want', 'desire', 'wish for'],
    'ensenar' : ['to teach', 'show'],
    'construir' : ['to construct', 'build'],
    'vender' : 'to sell',
    'representar' : 'to reporesent',
    'desaparecer' : ['to dissapear', 'vanish'],
    'mandar' : ['to send', 'order'],
    'andar' : ['to walk', 'function'],
    'preferir' : 'to prefer',
    'asegurar' : ['to assure', 'secure', 'insure'],
    'crecer' : ['to grow', 'increase'],
    'surgir' : ['to appear', 'spring'],
    'matar' : 'to kill',
    'entregar' : 'to deliver',
    'colocar' : ['to place', 'position'],
    'establecer' : 'to establish',
    'guardar' : ['to keep', 'save'],
    'indicar' : ['to initiate', 'start'],
    'bajar' : ['to come down', 'let down'],
    'notar' : 'to notice',
    'meter' : 'to put',
    'actuar' : 'to act',
    'pretender' : 'to attempt',
    'acordar' : ['to remember', 'remind'],
    'cortar' : 'to cut',
    'corresponder' : 'to correspond with',
    'romper' : 'to break',
    'adquirir' : ['to acquire', 'get'],
    'lanzar' : ['to throw', 'launch'],
    'aprovechar' : 'to take advantage of',
    'apoyar' : ['to support', 'lean on'],
    'negar' : ['to deny', 'refuse'],
    'avanzar' : ['to advance', 'progress'],
    'resolver' : ['to resolve', 'settle', 'work out'],
    'costar' : ['to cost', 'be hard'],
    'exigir' : 'to demand',
    'aumentar' : 'to increase',
    'recoger' : 'to pick up',
    'abandonar' : ['to abandon', 'leave'],
    'imponer' : ['to impose', 'enforce'],
    'obligar' : ['to obligate', 'force'],
    'aplicar' : 'to apply',
    'pertenecer' : 'to belong',
    'disponer' : ['to have means', 'dispose'],
    'expresar' : 'to express',
    'provocar' : ['to cause', 'provoke'],
    'defender' : ['to defend', 'protect'],
    'quitar' : ['to remove', 'take away'],
    'conservar' : ['to conserve', 'preserve'],
    'depender' : 'to depend on',
    'marcar' : ['to mark', 'note', 'dial'],
    'compartir' : 'to share',
    'consistir' : 'to consist of',
    'constituir' : 'to constitute',
    'cubrir' : 'to cover',
    'funcionar' :  ['to work', 'function'],
    'caber' : 'to fit',
    'atender' : ['to serve', 'attend to'],
    'insistir' : 'to insist on',
    'sentar' : ['to sit', 'seat'],
    'merecer' : ['to deserve', 'be worthy of'],
    'incluir' : 'to include',
    'cruzar' : 'to cross',
    'tender' : ['to tend to', 'lay out'],
    'anunciar' : ['to announce', 'advertise'],
    'despertar' : ['to wake up', 'arouse'],
    'comentar' : 'to comment on',
    'publicar' : 'to publish',
    'cargar' : ['to load', 'carry'],
    'participar' : 'to participate',
    'impedir' : ['to prevent', 'hinder'],
    'salvar' : ['to save', 'rescue'],
    'escapar' : 'to escape',
    'tirar' : ['to throw', 'pull'],
    'contestar' : ['to answer'],
    'preocupar' : 'to worry',
    'prestar' : 'to lend',
    'pesar' : 'to weigh',
    'exponer' : ['to expound', 'expose'],
    'viajar' : 'to travel',
    'separar' : ' to separate',
    'regresar' : 'to return',
    'contemplar' : 'to contemplate',
    'recorrer' : ['to travel', 'cover'],
    'durar' : 'to last',
    'retirar' : ['to take away', 'retire'],
    'permanecer' : ['to stay', 'remain'],
    'asistir' : 'to attend',
    'organizar' : 'to organize',
    'contener' : 'to contain',
    'visitar' : 'to visit',
    'informar' : 'to inform',
    'enviar' : 'to send',
    'cuidar' : 'to take care of',
    'intervenir' : 'to intervene', 
    'extender' : ['to exntend', 'spread'],
    'comprobar' : ['to verify', 'prove'],
    'dormir' : 'sleep',
    'discutir' : ['to argue', 'discuss'],
    'enfrentar' : ['to confront', 'face'],
    'conducir' : ['to lead', 'drive'],
    'firmar' : 'to sign',
    'respetar' : 'to respect',
    'sostener' : ['to support', 'hold up'],
    'advertir' : ['to notice', 'warn'],
    'transformar' : ['to transform', 'change'],
    'bastar' : 'to be sufficient',
    'mencionar' : ['to mention', 'cite'],
    'plantear' : ['to propose', 'present'],
    'probar' : ['to test', 'prove', 'try'],
    'manejar' : ['to drive', 'handle'],
    'unir' : ['to unite', 'join'],
    'caminar' : 'to walk',
    'coincidir' : ['to coincide', 'agree'],
    'llenar' : 'to fill',
    'dominar' : ['to dominate', 'master'],
    'medir' : 'to measure',
    'atravesar' : 'to cross',
    'destacar' : ['to emphasize', 'stand out'],
    'pronunciar' : 'to pronounce',
    'distinguir' : 'to distinguish',
    'introducir' : ['to introduce', 'bring in'],
    'comunicar' : 'to communicate',
    'invitar' : 'to invite',
    'instalar' : 'to install',
    'tardar' : ['to delay', 'take long'],
    'mejorar' : ['to improve', 'get better'],
    'emplear' : 'to employ',
    'convenir' : ['to be agreeable', 'be convenient'],
    'recuperar' : ['to recuperate', 'recover'],
    'definir' : 'to define',
    'superar' : ['to overcome', 'surpass'],
    'afirmar' : ['to assert', 'affirm'],
    'interpretar' : 'to interpret',
    'admitir' : 'to admit',
    'identificar' : 'to identify',
    'afectar' : 'to affect',
    'reducir' : 'to reduce',
    'montar' : ['to ride', 'mount', 'assemble']
}